services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: vasomap
      POSTGRES_USER: vasomap
      POSTGRES_PASSWORD: vasomap
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "vasomap"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
